from __future__ import annotations

from datetime import datetime
from pathlib import Path

from .models import DiscoveredPlan


def generate_markdown(
    plan: DiscoveredPlan, iteration: int, *, pending: bool = False
) -> str:
    """Generate a formatted markdown report for a plan."""
    now = datetime.now()
    status_label = (
        "Pending review (auto mode)" if pending else "Approved and saved by plan-finder"
    )

    files_list = "\n".join(f"- `{f}`" for f in plan.files_affected)
    steps_list = "\n".join(
        f"{i}. {step}" for i, step in enumerate(plan.implementation_steps, 1)
    )

    risks_section = ""
    if plan.risks:
        risks_list = "\n".join(f"- {r}" for r in plan.risks)
        risks_section = f"\n## Risks\n\n{risks_list}\n"

    return f"""\
# {plan.title}

> Generated by plan-finder on {now.strftime('%Y-%m-%d %H:%M:%S')}
> Iteration #{iteration} | Category: {plan.category.value} | Priority: {plan.priority}/5 | Effort: {plan.estimated_effort.value}

## Description

{plan.description}

## Rationale

{plan.rationale}

## Files Affected

{files_list}

## Implementation Steps

{steps_list}
{risks_section}
---
*{status_label}*
"""


def save_plan(
    plan: DiscoveredPlan,
    iteration: int,
    report_dir: Path,
    *,
    pending: bool = False,
) -> Path:
    """Save a plan as a markdown file. Returns the file path.

    If pending=True, saves to report_dir/pending/ instead of report_dir/.
    """
    target_dir = report_dir / "pending" if pending else report_dir
    target_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_title = (
        plan.title.lower().replace(" ", "-").replace("/", "-").replace("\\", "-")
    )
    safe_title = "".join(c for c in safe_title if c.isalnum() or c == "-")[:60]

    filename = f"{timestamp}_{safe_title}.md"
    filepath = target_dir / filename

    content = generate_markdown(plan, iteration, pending=pending)
    filepath.write_text(content, encoding="utf-8")

    return filepath
